[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "gotest.tools"
  version = "2.3.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.12.2"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"

[prune]
  go-tests = true
  unused-packages = true
