[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "master"
  name = "k8s.io/client-go"

[[constraint]]
  branch = "master"
  name = "k8s.io/helm"

[prune]
  go-tests = true
  unused-packages = true
