[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "gotest.tools"
  version = "2.3.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.12.2"

[prune]
  go-tests = true
  unused-packages = true
